package rtlspektrum;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : line 80</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("rtlpower") 
public class channel_solve extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public int upper() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public channel_solve upper(int upper) {
		this.io.setIntField(this, 0, upper);
		return this;
	}
	@Field(1) 
	public int lower() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public channel_solve lower(int lower) {
		this.io.setIntField(this, 1, lower);
		return this;
	}
	@Field(2) 
	public int bin_spec() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public channel_solve bin_spec(int bin_spec) {
		this.io.setIntField(this, 2, bin_spec);
		return this;
	}
	@Field(3) 
	public int hops() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public channel_solve hops(int hops) {
		this.io.setIntField(this, 3, hops);
		return this;
	}
	@Field(4) 
	public int bw_wanted() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public channel_solve bw_wanted(int bw_wanted) {
		this.io.setIntField(this, 4, bw_wanted);
		return this;
	}
	@Field(5) 
	public int bw_needed() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public channel_solve bw_needed(int bw_needed) {
		this.io.setIntField(this, 5, bw_needed);
		return this;
	}
	@Field(6) 
	public int bin_e() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public channel_solve bin_e(int bin_e) {
		this.io.setIntField(this, 6, bin_e);
		return this;
	}
	@Field(7) 
	public int downsample() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public channel_solve downsample(int downsample) {
		this.io.setIntField(this, 7, downsample);
		return this;
	}
	@Field(8) 
	public int downsample_passes() {
		return this.io.getIntField(this, 8);
	}
	@Field(8) 
	public channel_solve downsample_passes(int downsample_passes) {
		this.io.setIntField(this, 8, downsample_passes);
		return this;
	}
	@Field(9) 
	public double crop() {
		return this.io.getDoubleField(this, 9);
	}
	@Field(9) 
	public channel_solve crop(double crop) {
		this.io.setDoubleField(this, 9, crop);
		return this;
	}
	@Field(10) 
	public double crop_tmp() {
		return this.io.getDoubleField(this, 10);
	}
	@Field(10) 
	public channel_solve crop_tmp(double crop_tmp) {
		this.io.setDoubleField(this, 10, crop_tmp);
		return this;
	}
	public channel_solve() {
		super();
	}
	public channel_solve(Pointer pointer) {
		super(pointer);
	}
}
